version: '3'
services:

  app:
    build: .
    env_file: .env
    working_dir: /opt/app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/opt/app
    depends_on:
      - redis
      - rabbitmq
    ports:
      - "8000:8000"

  redis:
    image: 'redis:6-alpine'
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"

  rabbitmq:
    image: 'rabbitmq:3-management-alpine'
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
    ports:
      - "5672:5672"
      - "15672:15672"

  celery:
    build: .
    env_file: .env
    working_dir: /opt/app
    command: celery -A settings worker -l INFO
    volumes:
      - .:/opt/app
    depends_on:
      - redis
      - rabbitmq
